@MokaMetrics.API_HostAddress = http://localhost:8080

GET {{MokaMetrics.API_HostAddress}}/api/orders
Accept: application/json

###

GET {{MokaMetrics.API_HostAddress}}/api/iot
Accept: application/json

###

GET {{MokaMetrics.API_HostAddress}}/api/iot/health
Accept: application/json